import React from "react";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans as PlusJakartaSans } from "next/font/google";
import "@/styles/globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import Sidebar from "@/components/organisms/Sidebar";
import HeaderNav from "@/components/organisms/HeaderNav";
import SidebarProvider from "@/providers/sidebar-provider";
import SidebarSwitch from "@/components/molecules/SidebarSwitch";

const plusJakartaSans = PlusJakartaSans({
  weight: ["700", "500"], // Specify the needed font weights
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <div className="flex min-w-dvw flex-row">
              <Sidebar />
              <div>
                <HeaderNav />
                <main>{children}</main>
              </div>
            </div>
            <SidebarSwitch />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
